# Generated by Django 4.1.13 on 2024-03-08 06:13

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_heartrate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dateTime', models.DateField()),
                ('value', djongo.models.fields.JSONField()),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
